### ISSUE TITLE
Unable to connect to controller

### ISSUE THREAD

**Issue by sateeshruttala** [andrewleech/ha_magiqtouch#20] opened 2024-02-29 21:43 UTC
After giving user name and pwd it is not connecting

**Comment by andrewleech** [comment] 2024-03-11 01:42
This is likely a duplicate of https://github.com/andrewleech/ha_magiqtouch/issues/19

Seeley MagiQtouch completely changed their app server API so this integration needed a rewrite https://github.com/andrewleech/ha_magiqtouch/pull/21

**Closed as completed by andrewleech** 2024-03-11 01:42 UTC
